title: Hail Satan
author: Joshua Swongle
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Is your business busy retooling its model for the after life while this mortal coil passes you by?

# social links
twitter_username: joshercule # DO NOT include the @ character, or else the build will fail!
github_username:  joshercule # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
